package com.web.labportalbackend.admin.audit.enums;

public enum AuditAction {
    CHANGE_USER_ROLE,
    BAN_USER,
    UNBAN_USER,
    CREATE_LAB,
    UPDATE_LAB,
    DEACTIVATE_LAB,
    ASSIGN_MANAGER,
    UPDATE_SYSTEM_CONFIG,
    CREATE_SLOT,
    CANCEL_SLOT,
    REVIEW_APPLICATION,
    STUDENT_UPLOAD_REPORT,
    LEADER_REVIEW_REPORT,
    MANAGER_REVIEW_REPORT,
    STUDENT_UPLOAD_PRODUCT,
    CREATE_RESEARCH_PROJECT,
    UPDATE_RESEARCH_PROJECT,
    CREATE_RESEARCH_GROUP,
    UPDATE_RESEARCH_GROUP,
    EVALUATE_STUDENT,
    CREATE_RESEARCH_TASK,
    UPDATE_RESEARCH_TASK,
    UPDATE_RESEARCH_TASK_STATUS
}
