package com.web.labportalbackend.ai.enums;

public enum AiCapabilityEvidence {
    AUTHENTICATED_ACTOR,
    REGISTRY_PROFILE,
    SYSTEM_ROLE,
    CAPABILITY_CATALOG,
    DERIVED_RESOURCE,
    LAB_MEMBERSHIP,
    GROUP_MEMBERSHIP,
    GROUP_LEADERSHIP,
    OWNERSHIP,
    ASSIGNMENT,
    MANAGED_LAB,
    EXISTING_PERMISSION,
    NO_ADDITIONAL_GRANT,
    ACTION_RISK_BOUNDARY
}
