package com.web.labportalbackend.ai.enums;

public enum AiCapabilityDenialReason {
    MALFORMED_REQUEST,
    UNAUTHENTICATED,
    ACTOR_UNAVAILABLE,
    ACTOR_MISMATCH,
    UNKNOWN_ASSISTANT,
    ASSISTANT_DISABLED,
    ASSISTANT_MISCONFIGURED,
    ROLE_NOT_ALLOWED,
    DOMAIN_MISMATCH,
    UNKNOWN_CAPABILITY,
    ACTION_NOT_ALLOWED,
    RESOURCE_REQUIRED,
    RESOURCE_TYPE_MISMATCH,
    RESOURCE_UNAVAILABLE,
    RESOURCE_OUT_OF_SCOPE,
    NOT_OWNER,
    NOT_ASSIGNED,
    NOT_LAB_MEMBER,
    NOT_GROUP_MEMBER,
    NOT_GROUP_LEADER,
    NOT_MANAGED_LAB,
    PRIVATE_RESOURCE,
    EXPLICIT_GRANT_REQUIRED,
    PROHIBITED_ACTION
}
