package com.web.labportalbackend.notification.enums;

public enum NotificationEventType {
    TASK_ASSIGNED,
    TASK_STATUS_CHANGED,
    REPORT_SUBMITTED,
    REPORT_REVIEWED,
    PROPOSAL_SUBMITTED,
    PROPOSAL_APPROVED,
    PROPOSAL_REJECTED,
    AI_ACTION_STATUS_CHANGED,
    FACE_CHECKIN_SUCCEEDED,
    FACE_CHECKIN_FAILED,
    BOOKING_REQUESTED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_SESSION_COMPLETED,
    QR_CHECKIN_REQUESTED,
    QR_CHECKIN_REVIEWED
}
